In [115]:
from cluster import KMeans, make_clusters
import numpy as np

In [116]:
kmeans = KMeans(3, tol=1e-6, max_iter=100)

In [117]:
mat, labels = make_clusters()

In [118]:
random_centroid_x = np.random.uniform(low=np.min(mat[:, 0]), high=np.max(mat[:, 0]))

# Generate random y coordinate for initial centroid within range of data points
random_centroid_y = np.random.uniform(low=np.min(mat[:, 1]), high=np.max(mat[:, 1]))

# Create a 2D array with centroid x, y values
random_centroid_arr = np.array([[random_centroid_x, random_centroid_y]])

In [119]:
print(random_centroid_arr)

[[-10.60840815  10.38365128]]


In [120]:
from scipy.spatial.distance import cdist
dist = cdist(random_centroid_arr, mat, 'euclidean')

In [121]:
# Initialize an array of centroids with dimensions k x m
col_num = len(mat[0])
centroid_array = np.zeros(shape=(kmeans.k, col_num))
print(centroid_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [100]:
from scipy.spatial.distance import cdist
# Generate initial centroid array
init_centroid_array = kmeans._generate_init_centroid(mat)
print(init_centroid_array)

[[-0.18331639  7.72089421]]


In [101]:
# Add initial centroid array to array of centroids
centroid_array = np.append(centroid_array, init_centroid_array)
centroi

NameError: name 'centroi' is not defined

In [122]:
# already defined centroid_array to have dimension k=3 so while loop doesnt even start
# change while loop 
# Generate k number of centroids

max_iter_counter = 1

# Calculate distance from centroid to rest of points
dist = cdist(init_centroid_array, mat, 'euclidean')

# Square the distances between the random centroid and the rest of the points
square_dist = np.square(dist)

# Sum the squared the distances
sum_dist = np.sum(square_dist)

# Divide each element in the squared distances array by the sum of all the squared distances
prob_dist = square_dist / sum_dist

# Calculate the cumulative probability
cumulative_probs = prob_dist.cumsum()

# Choose a random number r
r = np.random.random()

# Find the first set of centroid coordinates
index = np.where(cumulative_probs >= r)[0][0]

# Returns new center
new_center = mat[index]

while max_iter_counter < kmeans.max_iter:

    while len(centroid_array) < kmeans.k:
        # Append new centroid array to centroid array
        np.append(centroid_array, new_centroid_array)
    
    # max_iter_counter
    max_iter_counter += 1

kmeans.centroids = centroid_array
print(kmeans.centroids)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [62]:
a = np.zeros(shape=(2,1))
print(a)

[[0.]
 [0.]]


In [65]:
a = np.append(a, [1,2])

In [66]:
print(a)

[0. 0. 1. 2.]


In [70]:
a = np.append(a, [3, 4])

In [71]:
print(a)

[0. 0. 1. 2. 3. 4. 3. 4.]


In [75]:
for index, item in enumerate(a):
    a[index] = 1

In [77]:
print(a)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [103]:
centers = []
initial_index = np.random.choice(range(mat.shape[0]), )
centers.append(mat[initial_index, :].tolist())
print(centers)

[[-9.571403695852785, 10.642187053192218]]


In [146]:
def generate_init_centroid(self, mat: np.ndarray) -> np.ndarray:
    # Generate random x coordinate for initial centroid within range of data points
    # random_centroid_x = np.random.uniform(low=np.min(mat[:, 0]), high=np.max(mat[:, 0]))

    # Generate random y coordinate for initial centroid within range of data points
    # random_centroid_y = np.random.uniform(low=np.min(mat[:, 1]), high=np.max(mat[:, 1]))

    # Create a 2D array with centroid x, y values
    # random_centroid_arr = np.array([[random_centroid_x, random_centroid_y]])

    centers = []
    initial_index = np.random.choice(range(mat.shape[0]), )
    centers.append(mat[initial_index, :].tolist())

    for i in range(kmeans.k - 1):
        dist = cdist(mat, np.array(centers))

        # Square the distances between the random centroid and the rest of the points
        square_dist = np.square(dist)

        # Sum the squared the distances
        sum_dist = np.sum(square_dist)

        # Divide each element in the squared distances array by the sum of all the squared distances
        prob_dist = square_dist / sum_dist

        # Calculate the cumulative probability
        cumulative_probs = prob_dist.cumsum()

        # Choose a random number r
        r = np.random.random()

        # Find the first set of coordinates
        index = np.where(cumulative_probs >= r)[0][0]

        new_centro
        centers.append(new_centroid.tolist())

    return np.array(centers)

In [147]:
centroids = generate_init_centroid(kmeans, mat)

525


IndexError: index 525 is out of bounds for axis 0 with size 500

In [148]:
print(centroids)

[[  0.58387655  -0.74497837]
 [-10.49214441   7.33088134]
 [  5.03075382   2.78115795]]
